### ISSUE TITLE
Cannot find module 'genie-toolkit'

### ISSUE THREAD

**Issue by pipip** [stanford-oval/almond-server#115]
Run stanfordoval/almond-server with docker-compose. 
Error at startup:

> yarn run v1.22.5
$ node main.js
internal/modules/cjs/loader.js:638
    throw err;
Error: Cannot find module 'genie-toolkit'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/almond/main.js:34:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12) 
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by gcampax** [comment]
Are you running the latest version of the docker image? That might not be building correctly since #114 . I will fix the build, meanwhile if you want to test the latest version of Almond I would recommend cloning the git repo and following the dev instructions instead. If you want a working version of Almond with docker, please use one of the stable tags.
