### ISSUE TITLE
Podman container failed on Ubuntu Mate 21.04 running image almond-server:latest

### ISSUE THREAD

**Issue by vivotan** [stanford-oval/almond-server#222]
Hi,

Do you have a stable tag for 2.0 available to try or how to solve below issue? Thanks.

latest tag details below.

`podman run --name almond -p 3000:3000 -v /dev/shm:/dev/shm -v $XDG_RUNTIME_DIR/pulse:/run/pulse --security-opt label=disable docker.io/stanfordoval/almond-server
`

Trying to pull docker.io/stanfordoval/almond-server:latest...
Getting image source signatures
Copying blob 8c741e919b67 done  
Copying blob 601bcd68608b done  
Copying blob a6768d4a64d8 done  
Copying blob d8fa339fd2c7 done  
Copying blob 468b46a59892 done  
Copying blob be361f394213 done  
Copying blob b595d4a792e8 done  
Copying config 07ea8c92d4 done  
Writing manifest to image destination
Storing signatures

> almond-server@2.0.1 start /opt/almond
> node dist/main.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'thingpedia'
Require stack:
- /opt/almond/dist/service/platform/index.js
- /opt/almond/dist/util/user.js
- /opt/almond/dist/frontend.js
- /opt/almond/dist/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/almond/dist/service/platform/index.js:51:25)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/almond/dist/service/platform/index.js',
    '/opt/almond/dist/util/user.js',
    '/opt/almond/dist/frontend.js',
    '/opt/almond/dist/main.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! almond-server@2.0.1 start: `node dist/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the almond-server@2.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/almond/.npm/_logs/2021-06-21T07_16_46_061Z-debug.log

**Comment by gcampax** [comment]
Yes, there is a docker tag for every version tagged in this repository. Specifically, v2.0.1 is the latest stable tag. You can find the list of all tags on the docker hub page: https://hub.docker.com/repository/docker/stanfordoval/almond-server

Re the "latest" tag, it looks like the build is currently non functional. Thanks for the report, I will investigate why it's silently creating a broken build...

**Comment by gcampax** [comment]
Hello again, and thanks for reporting this. I tested the latest build, and it appears to work correctly. I think this was a transient issue. Can you confirm that the latest build (with the `latest` tag) works for you? Thanks!
